version: '3'

services:
  server:
    build:
      context: .
    image: langchain_chatbot_example:latest
    container_name: langchain_chatbot_example
    ports:
      - "8001:8001"
    env_file:
      - .env
